### ISSUE TITLE
RuntimeError: size mismatch, m1: [2 x 4608], m2: [2048 x 1024] at /pytorch/aten/src/THC/generic/THCTensorMathBlas.cu:249

### ISSUE THREAD

**Issue by Myzhencai** [thangvubk/PESR#3]
I have changed the picture to 1920x1080 and 480x270 for trainning but I got this error:
Could you please help me out ,thanks ! Have a nice day :-).
![2019-06-20 11-39-27 的屏幕截图](https://user-images.githubusercontent.com/21084423/59816804-14f86280-9350-11e9-8364-240a04135963.png)

**Comment by thangvubk** [comment]
When the img size is different. You may have to change the discriminator structure to grt desired output shape.

**Comment by Myzhencai** [comment]
@thangvubk thanks for reply but when I changed the classify to 2x4608 I got this error:-)?
![Uploading 2019-06-19 23-54-40屏幕截图.png…]()
