### ISSUE TITLE
Out of CUDA memory error - any parameters to set?

### ISSUE THREAD

**Issue by sjscotti** [thangvubk/PESR#4]
Hi 
I am very interested in testing your approach and compare with other ones for some sample photos I have.  I am able to have it run for fairly small images, but the ones I really want to test are 640x360 and I get the "Out of CUDA memory" error during the process.  I only have 2GB of GPU memory so are there parameter settings of the program that will allow the test.py routine to run for this size image on my computer?   Also, is the 4x upscaling variable so that I could change it to 2x?
Thanks!
-Steve

**Comment by thangvubk** [comment]
The current model assumes that the upscaling factor of 4. You can change to 2x with some easy modifications.
